let name="Aakash";
let school="Crescent Public School";
let grade= 5;
let section= "B";
let rollnumber= 1;
math= 78;
english=67;
science=98;
console.log("__________________________________________________________");
console.log("|                 ***Report Card***                      |");
console.log("|   Name        :", name ,"                                |");
console.log("|   School      :", school ,"                |");
console.log("|   Grade       :", grade ,"                                     |");
console.log("|   Section     :", section ,"                                     |");   
console.log("|   Roll Number :", rollnumber ,"                                     |");
console.log("|   Mathematics :", math ,"                                    |");
console.log("|   English     :", english ,"                                    |");
console.log("|   Science     :", science ,"                                    |");
console.log("|________________________________________________________|");